require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'yvdlApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'react-native-cameraroll', :path => '../node_modules/@react-native-community/cameraroll'

  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'

  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

  pod 'react-native-ffmpeg', :path => '../node_modules/react-native-ffmpeg'

  pod 'RNShare', :path => '../node_modules/react-native-share'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  target 'yvdlAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'yvdlApp-tvOS' do
  # Pods for yvdlApp-tvOS

  target 'yvdlApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
